## IHMM testing outcomes

In [225]:
import numpy as np
from pymovements.events.detection.ihmm import ihmm
from pymovements.events.detection.idt import idt
from pymovements.events.detection.microsaccades import microsaccades
#from pymovements.gaze import from_numpy
from pymovements.synthetic import step_function
from pymovements.gaze.transforms_numpy import pos2vel

sampling_rate = 1000.0

In [226]:
'''positions = step_function(
         length=200, steps=[2, 5, 9, 111, 150],
         values=[(1., 2.), (2., 3.), (3., 4.), (1., 1.), (2., 2.)],
         start_value=(0., 0.),
     )'''

'positions = step_function(\n         length=200, steps=[2, 5, 9, 111, 150],\n         values=[(1., 2.), (2., 3.), (3., 4.), (1., 1.), (2., 2.)],\n         start_value=(0., 0.),\n     )'

### No fixations

In [227]:
positions = step_function(
    length=6,
    steps=[1, 2, 3, 4, 5],
    values=[
        (100., 100.),
        (-100., -100.),
        (100., -100.),
        (-100., 100.),
        (200., 0.),
    ],
    start_value=(0., 0.),
)

velocities = pos2vel(positions,sampling_rate=sampling_rate)

ihmmEvents = ihmm(velocities,reestimation=True,name="ihmm_fix")

idtEvents = microsaccades(positions,name="idt_fix")

D:\dionigi\Documents\Python scripts\pyMovementLab\pymovements\src\pymovements\events\detection\ihmm.py:238: RuntimeWarning: invalid value encountered in scalar divide
  trans[i, j] = np.log(numer / denom)

In [228]:
#print(len(velocities))
ihmmEvents

shape: (1, 4)
┌──────────┬───────┬────────┬──────────┐
│ name     ┆ onset ┆ offset ┆ duration │
│ ---      ┆ ---   ┆ ---    ┆ ---      │
│ str      ┆ i64   ┆ i64    ┆ i64      │
╞══════════╪═══════╪════════╪══════════╡
│ ihmm_fix ┆ 0     ┆ 5      ┆ 5        │
└──────────┴───────┴────────┴──────────┘

In [229]:
idtEvents

shape: (0, 4)
┌──────┬───────┬────────┬──────────┐
│ name ┆ onset ┆ offset ┆ duration │
│ ---  ┆ ---   ┆ ---    ┆ ---      │
│ str  ┆ i64   ┆ i64    ┆ i64      │
╞══════╪═══════╪════════╪══════════╡
└──────┴───────┴────────┴──────────┘

### One fixation

In [230]:
positions = step_function(
    length=200,
    steps=[20, 40, 60, 80, 100, 120, 140, 160, 180],
    values=[
        (10., 10.),
        (20., 5.),
        (30., 15.),
        (40., 0.),
        (50., 25.),
        (60., -10.),
        (70., 30.),
        (80., -20.),
        (90., 40.),
    ],
    start_value=(0., 0.),
)

velocities = pos2vel(positions,sampling_rate=sampling_rate)

ihmmEvents = ihmm(velocities,reestimation=True,name="ihmm_fix")

idtEvents = idt(positions,name="idt_fix")

In [231]:
ihmmEvents

shape: (10, 4)
┌──────────┬───────┬────────┬──────────┐
│ name     ┆ onset ┆ offset ┆ duration │
│ ---      ┆ ---   ┆ ---    ┆ ---      │
│ str      ┆ i64   ┆ i64    ┆ i64      │
╞══════════╪═══════╪════════╪══════════╡
│ ihmm_fix ┆ 0     ┆ 17     ┆ 17       │
│ ihmm_fix ┆ 22    ┆ 37     ┆ 15       │
│ ihmm_fix ┆ 42    ┆ 57     ┆ 15       │
│ ihmm_fix ┆ 62    ┆ 77     ┆ 15       │
│ ihmm_fix ┆ 82    ┆ 97     ┆ 15       │
│ ihmm_fix ┆ 102   ┆ 117    ┆ 15       │
│ ihmm_fix ┆ 122   ┆ 137    ┆ 15       │
│ ihmm_fix ┆ 142   ┆ 157    ┆ 15       │
│ ihmm_fix ┆ 162   ┆ 177    ┆ 15       │
│ ihmm_fix ┆ 182   ┆ 199    ┆ 17       │
└──────────┴───────┴────────┴──────────┘

In [232]:
idtEvents

shape: (0, 4)
┌──────┬───────┬────────┬──────────┐
│ name ┆ onset ┆ offset ┆ duration │
│ ---  ┆ ---   ┆ ---    ┆ ---      │
│ str  ┆ i64   ┆ i64    ┆ i64      │
╞══════╪═══════╪════════╪══════════╡
└──────┴───────┴────────┴──────────┘

## One big fixation

In [233]:
positions = step_function(
    length=200,
    steps=[20, 40, 60, 80, 100, 120, 140, 160, 180],
    values=[
        (10., 10.),
        (20., 5.),
        (30., 15.),
        (40., 0.),
        (50., 25.),
        (60., -10.),
        (70., 30.),
        (80., -20.),
        (90., 40.),
    ],
    start_value=(0., 0.),
)

velocities = pos2vel(positions,sampling_rate=sampling_rate)

ihmmEvents = ihmm(velocities,reestimation=True,name="ihmm_fix")

idtEvents = idt(positions,name="idt_fix")

In [234]:
ihmmEvents

shape: (10, 4)
┌──────────┬───────┬────────┬──────────┐
│ name     ┆ onset ┆ offset ┆ duration │
│ ---      ┆ ---   ┆ ---    ┆ ---      │
│ str      ┆ i64   ┆ i64    ┆ i64      │
╞══════════╪═══════╪════════╪══════════╡
│ ihmm_fix ┆ 0     ┆ 17     ┆ 17       │
│ ihmm_fix ┆ 22    ┆ 37     ┆ 15       │
│ ihmm_fix ┆ 42    ┆ 57     ┆ 15       │
│ ihmm_fix ┆ 62    ┆ 77     ┆ 15       │
│ ihmm_fix ┆ 82    ┆ 97     ┆ 15       │
│ ihmm_fix ┆ 102   ┆ 117    ┆ 15       │
│ ihmm_fix ┆ 122   ┆ 137    ┆ 15       │
│ ihmm_fix ┆ 142   ┆ 157    ┆ 15       │
│ ihmm_fix ┆ 162   ┆ 177    ┆ 15       │
│ ihmm_fix ┆ 182   ┆ 199    ┆ 17       │
└──────────┴───────┴────────┴──────────┘

In [235]:
idtEvents

shape: (0, 4)
┌──────┬───────┬────────┬──────────┐
│ name ┆ onset ┆ offset ┆ duration │
│ ---  ┆ ---   ┆ ---    ┆ ---      │
│ str  ┆ i64   ┆ i64    ┆ i64      │
╞══════╪═══════╪════════╪══════════╡
└──────┴───────┴────────┴──────────┘

### Trailing and ending fixations

In [236]:
positions = step_function(
    length=200,
    steps=[20, 40, 60, 80, 100, 120, 140, 160, 180],
    values=[
        (10., 10.),
        (20., 5.),
        (30., 15.),
        (40., 0.),
        (50., 25.),
        (60., -10.),
        (70., 30.),
        (80., -20.),
        (90., 40.),
    ],
    start_value=(0., 0.),
)

velocities = pos2vel(positions,sampling_rate=sampling_rate)

ihmmEvents = ihmm(velocities,reestimation=True,name="ihmm_fix")

idtEvents = idt(positions,name="idt_fix")

In [237]:
ihmmEvents

shape: (10, 4)
┌──────────┬───────┬────────┬──────────┐
│ name     ┆ onset ┆ offset ┆ duration │
│ ---      ┆ ---   ┆ ---    ┆ ---      │
│ str      ┆ i64   ┆ i64    ┆ i64      │
╞══════════╪═══════╪════════╪══════════╡
│ ihmm_fix ┆ 0     ┆ 17     ┆ 17       │
│ ihmm_fix ┆ 22    ┆ 37     ┆ 15       │
│ ihmm_fix ┆ 42    ┆ 57     ┆ 15       │
│ ihmm_fix ┆ 62    ┆ 77     ┆ 15       │
│ ihmm_fix ┆ 82    ┆ 97     ┆ 15       │
│ ihmm_fix ┆ 102   ┆ 117    ┆ 15       │
│ ihmm_fix ┆ 122   ┆ 137    ┆ 15       │
│ ihmm_fix ┆ 142   ┆ 157    ┆ 15       │
│ ihmm_fix ┆ 162   ┆ 177    ┆ 15       │
│ ihmm_fix ┆ 182   ┆ 199    ┆ 17       │
└──────────┴───────┴────────┴──────────┘

In [238]:
idtEvents

shape: (0, 4)
┌──────┬───────┬────────┬──────────┐
│ name ┆ onset ┆ offset ┆ duration │
│ ---  ┆ ---   ┆ ---    ┆ ---      │
│ str  ┆ i64   ┆ i64    ┆ i64      │
╞══════╪═══════╪════════╪══════════╡
└──────┴───────┴────────┴──────────┘

## Toy dataset

In [239]:
ihmmEvents = []

idtEvents = []

In [240]:
ihmmEvents

[]

In [241]:
idtEvents

[]

## Regular Dataset

In [242]:
ihmmEvents = []

idtEvents = []

In [243]:
ihmmEvents

[]

In [244]:
idtEvents

[]